CREATE TABLE t_article(
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(32) NOT NULL,
  TYPE VARCHAR(32) NOT NULL,
  content TEXT
);

CREATE TABLE t_user_agreement(
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  article_id INT
);