logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-6level%logger{0}.%M:%L - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-6level%logger{0}.%M:%L - %msg%n"
server:
  port: 11025
  servlet:
    context-path: /litongjava-spring-boot-ueditor
spring:
  application:
    name: litongjava-spring-boot-ueditor
  main:
    banner-mode: "off"
  devtools:
    restart:
      trigger-file: trigger.txt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.9/litongjava_spring_boot_ueditor?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&useSSL=false
    username: root
    password: robot_123456#
  web:
    resources:
      static-locations: classpath:/litongjava-spring-boot-ueditor
mybatis-plus:
  global-config:
    banner: false # 是否显示mybatis-plus的图标
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

project:
  user:
    name: admin
    password: robot_123456
