logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-6level%logger{0}.%M:%L - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-6level%logger{0}.%M:%L - %msg%n"
server:
  port: 11025
  context-path: /litongjava-spring-boot-ueditor
spring:
  application:
    name: litongjava-spring-boot-ueditor
  main:
    banner-mode: "off"
  devtools:
    restart:
      trigger-file: trigger.txt
  resources:
    static-locations: classpath:/litongjava-spring-boot-ueditor/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/litongjava_spring_boot_ueditor?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 
mybatis-plus:
  global-config:
    banner: false # 是否显示mybatis-plus的图标
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl